'use client';

import { useState, useEffect } from 'react';
import { DashboardLayout } from '@/components/layouts/DashboardLayout';
import { Card } from '@/components/ui/Card';
import { generateInsights, type Insight, getInsightColor } from '@/lib/insights-engine';

const MOCK_DAILY_STATS = {
  keyboardPresses: 12453,
  tabsOpened: 47,
  browsingTimeMinutes: 285,
  sessionDurationMinutes: 420,
};

export default function InsightsPage() {
  const [insights, setInsights] = useState<Insight[]>([]);
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);

  useEffect(() => {
    // Generate insights from mock data
    const generated = generateInsights(MOCK_DAILY_STATS);
    setInsights(generated);
  }, []);

  const filtered =
    selectedCategory === null
      ? insights
      : insights.filter((i) => i.category === selectedCategory);

  const categories = Array.from(new Set(insights.map((i) => i.category)));

  return (
    <DashboardLayout>
      <div className="space-y-8">
        <div>
          <h1 className="text-4xl font-bold mb-2">Insights</h1>
          <p className="text-gray-400">
            Observations about your digital behavior patterns
          </p>
        </div>

        {/* Category Filter */}
        <div className="flex gap-2 overflow-x-auto pb-2">
          <button
            onClick={() => setSelectedCategory(null)}
            className={`px-4 py-2 rounded-lg whitespace-nowrap transition ${
              selectedCategory === null
                ? 'bg-[#7C3AED] text-white'
                : 'bg-[#111827] text-gray-300 hover:bg-[#1A1A1F]'
            }`}
          >
            All
          </button>
          {categories.map((cat) => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`px-4 py-2 rounded-lg whitespace-nowrap capitalize transition ${
                selectedCategory === cat
                  ? 'bg-[#7C3AED] text-white'
                  : 'bg-[#111827] text-gray-300 hover:bg-[#1A1A1F]'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        {/* Insights Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          {filtered.length > 0 ? (
            filtered.map((insight, idx) => {
              const colorMap = {
                keyboard: 'border-purple-500',
                tabs: 'border-cyan-500',
                browsing: 'border-green-500',
                session: 'border-orange-500',
                pattern: 'border-pink-500',
              };

              return (
                <Card
                  key={idx}
                  className={`border-l-4 ${colorMap[insight.category]}`}
                >
                  <div className="flex items-start gap-4">
                    <div className="text-4xl">{insight.emoji}</div>
                    <div className="flex-1">
                      <p className="text-lg font-medium leading-relaxed">
                        {insight.text}
                      </p>
                      <p className="text-xs text-gray-500 mt-3 capitalize">
                        {insight.category} insight • Today
                      </p>
                    </div>
                  </div>
                </Card>
              );
            })
          ) : (
            <Card className="md:col-span-2">
              <p className="text-center text-gray-400 py-8">
                No insights yet. Keep tracking to discover patterns!
              </p>
            </Card>
          )}
        </div>

        {/* How It Works */}
        <Card>
          <h2 className="text-xl font-semibold mb-4">How Insights Work</h2>
          <div className="space-y-3 text-gray-300">
            <p>
              <strong>Rule-Based Analysis:</strong> Insights are generated by
              analyzing patterns in your keyboard activity, tab usage, and
              browsing time.
            </p>
            <p>
              <strong>Privacy First:</strong> All analysis happens locally on
              your device. No personal data is sent to external AI services.
            </p>
            <p>
              <strong>Continuous Learning:</strong> More data = better insights.
              Keep the extension running to build a complete picture of your
              digital habits.
            </p>
          </div>
        </Card>

        {/* Daily Stats Reference */}
        <Card>
          <h2 className="text-xl font-semibold mb-4">Today's Stats Summary</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div>
              <p className="text-gray-400 text-sm mb-2">Keyboard Presses</p>
              <p className="text-2xl font-bold text-[#7C3AED]">
                {MOCK_DAILY_STATS.keyboardPresses.toLocaleString()}
              </p>
            </div>
            <div>
              <p className="text-gray-400 text-sm mb-2">Tabs Opened</p>
              <p className="text-2xl font-bold text-[#06B6D4]">
                {MOCK_DAILY_STATS.tabsOpened}
              </p>
            </div>
            <div>
              <p className="text-gray-400 text-sm mb-2">Browsing Time</p>
              <p className="text-2xl font-bold text-[#22C55E]">
                {Math.round(MOCK_DAILY_STATS.browsingTimeMinutes / 60)}h{' '}
                {MOCK_DAILY_STATS.browsingTimeMinutes % 60}m
              </p>
            </div>
            <div>
              <p className="text-gray-400 text-sm mb-2">Session Duration</p>
              <p className="text-2xl font-bold text-[#F97316]">
                {Math.round(MOCK_DAILY_STATS.sessionDurationMinutes / 60)}h
              </p>
            </div>
          </div>
        </Card>
      </div>
    </DashboardLayout>
  );
}
